### PR TITLE
Feature/veggies 

### PR DESCRIPTION
**Pull request by shravanipagilla**

### CODE REVIEW

**Review by alexchessmaster — APPROVED** [review]
in your first commit, you modified `onion` and add 2 more lines and in your second commit you modified `onion` again, you did not delete any lines. it's totally fine. if you want you can delete some lines and make commit and PR just for practice. if you like it.
You did a good job, remember to practice `git cherry-pick` and `git revert` at home.

**Review by marta-ov — APPROVED** [review]
Good work Shravani! :D
You can merge this PR and then create a new one from `git-week2` to `main` and merge that too :)

**Comment by shravanipagilla** [comment]
> in your first commit, you modified `onion` and add 2 more lines and in your second commit you modified `onion` again, you did not delete any lines. it's totally fine. if you want you can delete some lines and make commit and PR just for practice. if you like it. You did a good job, remember to practice `git cherry-pick` and `git revert` at home.

@materialsmoke  . Thank you so much for the time to review my code.  and also I did the `git cherry-pick` and `git revert` assignments too.
Thank you :)

**Comment by shravanipagilla** [comment]
> Good work Shravani! :D You can merge this PR and then create a new one from `git-week2` to `main` and merge that too :)

@marta-ov Thank you so much, Marta .. :)

**Pull request merged**
